main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('distribusi-tugas/', views.DistribusiTugasView.as_view(), name='distribusi_tugas'),
    path('', views.index, name='landing_page'),
]

sivax_b08/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger5/', include('trigger5.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger1/', include('login.urls')),
    path('trigger4/', include('trigger4.urls')),
]

trigger4/urls.py
from django.urls import path

from . import views

app_name = 'trigger4'

urlpatterns = [
    path('pengguna/tiket/tiket_saya', views.tiket_saya, name='tiket_saya'),
    path('pengguna/tiket/detail/(?P<instansi>[0-9]+)$/(?P<jadwal>[0-9]+)$/(?P<nomor>[0-9]+)$/(?P<status>[0-9]+)$', views.detail_tiket, name='detail_tiket'),
    path('pengguna/penjadwalan/daftar_jadwal', views.daftar_jadwal_terdaftar, name="daftar_jadwal_terdaftar"),
    path('pengguna/penjadwalan/detail/(?P<instansi>[0-9]+)$/(?P<jadwal>[0-9]+)$', views.detail_jadwal, name='detail_jadwal'),
    path('pengguna/tiket/create/(?P<instansi>[0-9]+)$/(?P<jadwal>[0-9]+)$', views.create_tiket, name="create_tiket"),
    path('admin/vaksin/tambah_vaksin', views.tambah_vaksin, name="tambah_vaksin"),
]

trigger4/models.py
from django.db import models

# Create your models here.

trigger4/views.py
from django.http import response
from django.shortcuts import redirect, render
from django.db import connection
from django.contrib.messages.api import add_message
from django.contrib import messages
import datetime

# Create your views here.
def create_tiket(request, instansi, jadwal):
    with connection.cursor() as cursor:
        email = request.session.get('email')
        cursor.execute("SET search_path to sivax")
        cursor.execute(f"""
                       SELECT *
                       FROM WARGA
                       WHERE email = '{email}'
                       """)
        if len(cursor.fetchall()) == 0:
            messages.add_message(request, messages.WARNING, "Registrasi sebagai warga dahulu sebelum mendaftar vaksinasi")
            cursor.execute("SET search_path TO PUBLIC")
            return redirect("trigger4:detail_jadwal", instansi, jadwal)
        cursor.execute(f"""
                       SELECT kode
                       FROM INSTANSI
                       WHERE nama_instansi = '{instansi}'""")
        kode_instansi = cursor.fetchall()[0][0]
        cursor.execute("""
                       SELECT COUNT(*)
                       FROM TIKET
                       """)
        data_no_tiket = cursor.fetchall()[0][0]
        no_tiket = 'tkt0' + str(data_no_tiket+1)
        try:
            cursor.execute(f"""
                           INSERT INTO TIKET(email, no_tiket, kode_instansi, kode_status, tgl_waktu) VALUES
                           ('{email}', '{no_tiket}', '{kode_instansi}', 01, '{jadwal}')""")
        except:
            messages.add_message(request, messages.WARNING, "Anda sudah vaksin dosis ke-2 atau vaksin dosis pertama Anda masih dalam rentang waktu 14 hari ke belakang")
            return redirect("trigger4:detail_jadwal", instansi, jadwal)
        cursor.execute("SET search_path to public")
    return redirect("trigger4:tiket_saya")

def detail_jadwal(request, instansi, jadwal):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path TO SIVAX")
        cursor.execute(f"""
                       SELECT kode
                       FROM INSTANSI
                       WHERE nama_instansi ='{instansi}'
                       """)
        kode_instansi = cursor.fetchall()[0][0]
        
        cursor.execute(f"""
                       SELECT *
                       FROM PENJADWALAN
                       WHERE kode_instansi = '{kode_instansi}' AND tanggal_waktu = '{jadwal}'""")
        penjadwalan = cursor.fetchall()[0]
        
        cursor.execute(f"""
                       SELECT nama
                       FROM LOKASI_VAKSIN
                       WHERE kode = '{penjadwalan[6]}'""")
        lokasi_vaksin = cursor.fetchall()[0][0]
        
        context = {
            'nama_instansi' : instansi,
            'jadwal' : jadwal,
            'kuota' : penjadwalan[2],
            'kategori' : penjadwalan[3],
            'nama_lokasi' : lokasi_vaksin,
        }
        cursor.execute("set search_path TO PUBLIC")
    return render(request, 'trigger4/pengguna/detail_jadwal.html', context)

def daftar_jadwal_terdaftar(request):
    context = dict()
    context['jadwal_vaksinasi'] = []
    with connection.cursor() as cursor:
        cursor.execute("SET search_path TO SIVAX")
        cursor.execute("""
                       SELECT *
                       FROM PENJADWALAN
                       WHERE status = 'pengajuan disetujui'
                       """)
        jadwal = cursor.fetchall()
        
        for i in range(len(jadwal)):
            cursor.execute("""
                           SELECT *
                           FROM INSTANSI
                           WHERE kode = %s""", [jadwal[i][0]])
            instansi = cursor.fetchall()
            context['jadwal_vaksinasi'].append([
                instansi[0][1], jadwal[i][1], jadwal[i][2]
            ])
        cursor.execute("SET search_path TO PUBLIC")
    return render(request, 'trigger4/pengguna/daftar_jadwal_terdaftar.html', context )

def tiket_saya(request):
    context = dict()
    context['kumpulan_tiket'] = []
    with connection.cursor() as cursor:
        email = request.session.get('email')
        cursor.execute("SET search_path to SIVAX")
        cursor.execute(f"""
                       SELECT * 
                       FROM TIKET
                       WHERE email = '{email}'
                       """)
        my_ticket = cursor.fetchall()
        
        for i in range(len(my_ticket)):
            cursor.execute("""
                           SELECT *
                           FROM INSTANSI
                           WHERE kode = %s""", [my_ticket[i][2]])
            instansi = cursor.fetchall()
            cursor.execute("""SELECT *
                           FROM STATUS_TIKET
                           WHERE kode = %s""", [my_ticket[i][3]])
            status_tiket = cursor.fetchall()
            context['kumpulan_tiket'].append([
                my_ticket[i][0], my_ticket[i][1], instansi[0][1], status_tiket[0][1], my_ticket[i][4]
            ])
        cursor.execute("SET search_path to public")
    return render(request, 'trigger4/pengguna/tiket_saya.html', context=context)

def detail_tiket(request, instansi, jadwal, nomor, status):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path TO SIVAX")
        cursor.execute(f"""
                       SELECT kode
                       FROM INSTANSI
                       WHERE nama_instansi = '{instansi}'
                       """)
        kode_instansi = cursor.fetchall()[0][0]
        cursor.execute(f"""
                       SELECT *
                       FROM PENJADWALAN
                       WHERE kode_instansi = '{kode_instansi}' AND tanggal_waktu = '{jadwal}'
                       """)
        penjadwalan = cursor.fetchall()[0]
        cursor.execute(f"""
                       SELECT nama
                       FROM LOKASI_VAKSIN
                       WHERE kode = '{penjadwalan[6]}'
                       """)
        nama_lokasi = cursor.fetchall()[0][0]
        
        context = {
            'nama_instansi' : instansi,
            'jadwal' : jadwal,
            'kuota' : penjadwalan[2],
            'kategori' : penjadwalan[3],
            'nama_lokasi' : nama_lokasi,
            'nomor_tiket' : nomor,
            'status_tiket' : status,
        }
        cursor.execute("SET search_path to public")
    return render(request, 'trigger4/pengguna/detail_tiket.html', context)

def tambah_vaksin(request):
    is_admin = False
    for i in request.session.get('roles'):
        if i == 'admin':
            is_admin = True
    if is_admin == False:
        return redirect("main:distribusi_tugas")
    
    context = dict()
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIVAX")
        cursor.execute("""SELECT COUNT(*)
                       FROM VAKSIN
                       """)
        data_kode = cursor.fetchall()[0][0]
        kode_vaksin = 'vcn0' + str(data_kode+1)
        context['kode_vaksin'] = kode_vaksin
        cursor.execute("SET search_path to public")
    
    if request.method == "POST":
        with connection.cursor() as cursor:
            cursor.execute("set search_path to sivax")
            try:
                cursor.execute(f"""
                               INSERT INTO VAKSIN (kode, nama, nama_produsen, no_edar, freq_suntik, stok) VALUES
                               ('{kode_vaksin}', '{request.POST["nama_vaksin"]}', '{request.POST["produsen"]}',
                               '{request.POST["no_edar"]}', '{request.POST["stok"]}', '{request.POST["frekuensi"]}')
                               """)
                return redirect("trigger2:admin-vaksin")
            except:
                messages.add_message(request, messages.WARNING, f"Sistem sedang tidak baik-baik saja, mohon coba lain waktu")
            cursor.execute("set search_path to public")
    return render(request, 'trigger4/admin/tambah_vaksin.html', context)

def delete_vaksin(request, kode):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path TO SIVAX")
        try:
            cursor.execute(f"""
                           DELETE FROM VAKSIN
                           WHERE kode = '{kode}'""")
        except:
            messages.add_message(request, messages.WARNING, f"Gagal menghapus Vaksin {kode}")
            cursor.execute("SET search_path TO PUBLIC")
        return redirect("trigger2:admin-vaksin")

trigger4/templates/trigger4/admin/tambah_vaksin.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tambah Vaksin</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>

    <body>
        {% block content %}
            {% include 'message.html' %}
            <style>
            form {
                padding: 5rem;
            }
            </style>
            <form action="{% url 'trigger4:tambah_vaksin' %}" method="POST">
                {% csrf_token %}
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td colspan="2" class="field-label text-center">
                                <h4>TAMBAH VAKSIN</h4>
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <label class="field-label">Kode</label>
                            </td>
                            <td>
                                <label class="field-label">{{ kode_vaksin }}</label>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="field-label">Nama Vaksin</label>
                            </td>
                            <td>
                                <input type="text" name="nama_vaksin" class="form-control" value="{{request.POST.nama_vaksin}}" placeholder="Nama Vaksin..." aria-label="Nama Vaksin" required>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="field-label">Produsen</label>
                            </td>
                            <td>
                                <input type="text" name="produsen" value="{{request.POST.produsen}}" class="form-control" placeholder="Nama Produsen..." aria-label="Produsen" required>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="field-label">No. Edar</label>
                            </td>
                            <td>
                                <input type="text" name="no_edar" value="{{request.POST.no_edar}}" class="form-control" placeholder="No. Edar..." aria-label="No. Edar" required>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="field-label">Stok</label>
                            </td>
                            <td>
                                <input type="text" name="stok" value="{{request.POST.stok}}" class="form-control" placeholder="Stok..." aria-label="Stok" required>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="field-label">Frekuensi</label>
                            </td>
                            <td>
                                <input type="text" name="frekuensi" value="{{request.POST.frekuensi}}" class="form-control" placeholder="Frekuensi..." aria-label="Frekuensi" required>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <div class="d-grid gap-2 col-6 mx-auto">
                <button class="btn btn-success" id="submit-button" type="submit">TAMBAH</button>
            </div>
            </form>

        {% endblock content %}
        {% block scripts %}
        {% include 'script.html' %}
        {% endblock scripts %}
    </body>
</html>