main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('distribusi-tugas/', views.DistribusiTugasView.as_view(), name='distribusi_tugas'),
    path('', views.index, name='landing_page'),
]

sivax_b08/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger5/', include('trigger5.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger1/', include('login.urls')),
    path('trigger4/', include('trigger4.urls')),
]

trigger4/urls.py
from django.urls import path

from . import views

app_name = 'trigger4'

urlpatterns = [
    path('pengguna/tiket/tiket_saya', views.tiket_saya, name='tiket_saya'),
    path('pengguna/tiket/detail/(?P<instansi>[0-9]+)$/(?P<jadwal>[0-9]+)$/(?P<nomor>[0-9]+)$/(?P<status>[0-9]+)$', views.detail_tiket, name='detail_tiket'),
    path('pengguna/penjadwalan/daftar_jadwal', views.daftar_jadwal_terdaftar, name="daftar_jadwal_terdaftar"),
    path('pengguna/penjadwalan/detail/(?P<instansi>[0-9]+)$/(?P<jadwal>[0-9]+)$', views.detail_jadwal, name='detail_jadwal'),
    path('pengguna/tiket/create/(?P<instansi>[0-9]+)$/(?P<jadwal>[0-9]+)$', views.create_tiket, name="create_tiket"),
    path('admin/vaksin/tambah_vaksin', views.tambah_vaksin, name="tambah_vaksin"),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.db import connection
from django.views.generic.base import View
from django.http.response import HttpResponseNotFound, HttpResponseRedirect, JsonResponse

def index(request):
    return render(request, 'main/landing_page.html')

def my_custom_sql(self):
    with connection.cursor() as cursor:
        cursor.execute("UPDATE bar SET foo = 1 WHERE baz = %s", [self.baz])
        cursor.execute("SELECT foo FROM bar WHERE baz = %s", [self.baz])
        row = cursor.fetchone()

class DistribusiTugasView(View):
    def get(self, request):
        context = {}
        context['email'] = request.session.get('email') 
        # return email kalau ada
        context['roles'] = request.session.get('roles') 
        # return role kalau ada. contoh: ['admin', 'panitia', 'warga', 'nakes']
        return render(request, 'main/home.html', context)

    def post(self,request):
        # Ini buat logout
        try:
            del request.session['email']
            del request.session['roles']
        except:
            pass
        return HttpResponseRedirect('/trigger1/login')

def landing_page(request):
    return render(request, 'main/landing_page.html')

main/templates/main/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>Landing Page</title>
  </head>
  <body class="py-16 px-32">
    {% if roles|length > 0 %}
      <div class="flex justify-between">
        <div class="w-1/2">
          <h3>HI {{ email }} !</h3>
          <h3>Your Role is:</h3>
          <ul class="list-inside"> 
            {% for role in roles %}
              <li class="list-disc"> {{ role }} </li>
            {% endfor %}
          </ul>
        </div>
        <div class="w-1/2 flex justify-end">
          <form action="" method="POST">
            {% csrf_token %}
            <button type="submit" class="bg-red-400 text-white font-bold px-8 py-3" > Logout </button>
          </form>
        </div>
      </div>
      {% else %}
      <h1>You're not logged in!</h1>
    {% endif %}
    <h1 class="font-bold text-2xl text-center">Sivac Basdat B08</h1>
    <br />
    <table class="table-fixed w-11/12 mx-auto text-center">
      <thead>
        <tr>
          <th class="w-1/12">No Trigger</th>
          <th class="w-1/12">No Fitur</th>
          <th class="w-1/3">Nama Fitur</th>
          <th class="w-1/6">Link</th>
          <th class="w-2/3">Penanggung Jawab</th>
        </tr>
      </thead>
      <tbody>
        <tr class="">
          <td>1</td>
          <td class="">1</td>
          <td class="">Login and Logout</td>
          <td class="">
            <a class="underline text-blue-500" href='/trigger1/login'>[User]</a>
          </td>
          <td>Gitan Sahl Tazakha Wijaya (2006596522)</td>
        </tr>
        <tr class="">
          <td>1</td>
          <td class="">2</td>
          <td class="">Registrasi Pengguna</td>
          <td class="">
            <a class="underline text-blue-500" href='/trigger1/register'>[User]</a>
          </td>
          <td>Gitan Sahl Tazakha Wijaya (2006596522)</td>
        </tr>
        <tr class="">
          <td>2</td>
          <td class="">3</td>
          <td class="">CRU Penjadwalan</td>
          <td class="">
            <div></div>
            <a class="underline text-blue-500" href="{% url 'panitia-penjadwalan' %}">[Panitia] </a>
            <a class="underline text-blue-500" href="{% url 'admin-penjadwalan' %}"> [Admin]</a>
          </td>
          <td>Zidan Kharisma Adidarma (2006463881)</td>
        </tr>
        <tr class="">
          <td>2</td>

          <td class="">4</td>
          <td class="">CRUD Distribusi</td>
          <td class="">
            <a class="underline text-blue-500" href="{% url 'admin-distribusi' %}">[Admin]</a>
          </td>
          <td>Zidan Kharisma Adidarma (2006463881)</td>
        </tr>
        <tr class="">
          <td>2</td>

          <td class="">5</td>
          <td class="">RU Vaksin</td>
          <td class="">
            <a class="underline text-blue-500" href="{% url 'admin-vaksin' %}">[Admin]</a>
          </td>
          <td>Zidan Kharisma Adidarma (2006463881)</td>
        </tr>
        <tr class="">
          <td>5</td>

          <td class="">11</td>
          <td class="">RU Tiket</td>
          <td class="">
            <a class="underline text-blue-500" href="{% url 'tiket_vaksin' %}">[Nakes]</a>
          </td>
          <td>Fayza Hanifah(1906399726)</td>
        </tr>
        <tr class="">
          <td>5</td>

          <td class="">12</td>
          <td class="">CR Kartu Vaksin</td>
          <td class="">
            <a class="underline text-blue-500" href="{% url 'kartu_vaksin' %}">[Pengguna]</a>
          </td>
          <td>Fayza Hanifah(1906399726)</td>
        </tr>
        <tr class="">
          <td>4</td>

          <td class="">10</td>
          <td class="">CD Vaksin</td>
          <td class="">
            <a class="underline text-blue-500" href='/trigger4/admin/vaksin/tambah_vaksin'>[Admin]</a>
          </td>
          <td>Gitan Sahl Tazakha Wijaya (2006596522)</td>
        </tr>
        <tr class="">
          <td>4</td>

          <td class="">9</td>
          <td class="">CR Tiket</td>
          <td class="">
            <a class="underline text-blue-500" href={% url 'trigger4:tiket_saya' %}>[Pengguna|Tiket Saya]</a>
            <a class="underline text-blue-500" href={% url 'trigger4:daftar_jadwal_terdaftar' %}>[Pengguna|Daftar Vaksinasi]</a>
          </td>
          <td>Gitan Sahl Tazakha Wijaya (2006596522)</td>
        </tr>
        

      </tbody>
    </table>
    {% comment %} end table {% endcomment %}
  </body>
</html>

main/templates/main/landing_page.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>SIVAX</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock meta %}

{% block content %}
  <div class='mt-5'>
    <div class='p-5'>
      <div class='mt-5'>
        <div class='p-5'>
          <h1 class ='text-center mt-5'>WELCOME TO SIVAX B08</h2>
          <p class='text-center mt-1'>Official Vaccine's Website</p>
          <div class='text-center p-5'>
            <a href='/trigger1/login' class='btn btn-success mr-2'>Login</a>
            <a href="/trigger1/register" class='btn btn-primary mx-2'>Register</a>
            <a href="/distribusi-tugas" class='btn btn-primary ml-2'>Distribusi Tugas</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
{% include 'script.html' %}
{% endblock scripts %}